### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [aidin36/simpletextcrypt#13]
https://f-droid.org/wiki/index.php?title=com.aidinhut.simpletextcrypt/lastbuild_11&oldid=282308

**Comment by licaon-kter** [comment]
But 12 did, so not sure why I missed that.

**Comment by aidin36** [comment]
F-Droid was still trying to build that tag. I removed the faulty tag.
Thanks for mentioning it.
