### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [aidin36/simpletextcrypt#15]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by aidin36** [comment]
Sorry that I didn't answer this.
Thanks for the suggestion. (: I will add them when I found some free time.

**Comment by mondlicht-und-sterne** [comment]
not bad. it was just information.
