### ISSUE TITLE
User shouldn't have to tap on Unlock button

### ISSUE THREAD

**Issue by aidin36** [aidin36/simpletextcrypt#2]
In ``LockActivity``, user has to tap on ``Unlock`` button. It would be easier for her to just tap the tick (enter) button on the keyboard.

**Comment by waqas** [comment]
I installed it for the first time and it is asking me to unlock. I do not have any passcode set at device level and certainly not at this app. How do I log in?

**Comment by aidin36** [comment]
I forgot to mention that anywhere! The default passcode is "1111". I will fix that.
Thanks for the feedback (-:

P.S: It would be better to open a new issue, since it wasn't related to this topic.

**Comment by waqas** [comment]
Yeah, sorry about that.
