### ISSUE TITLE
Description at F-Droid mentions encryption algorithm, but not key derivation scheme.

### ISSUE THREAD

**Issue by vi** [aidin36/simpletextcrypt#5]
Assuming this is an app to encrypt a text using user-provided password, the derivation scheme is almost as important as the encryption.

I recomment using a new, memory-aware one.

**Comment by aidin36** [comment]
Thanks for your feed back (:
You're right. I should write more details about the encryption in the documents (README file, actually.)

Right now, the app takes the key itself from the user. A 32 character-long string. This can be considered a truly random key, and secure.
But, recently I was researching on the topic, and found out that a human can only write printable ASCII characters. Thus, the key would have only a subset of possible characters (bytes). It can become more secure by passing it through a KDF algorithm.

I'm re-thinking this part.

**Comment by aidin36** [comment]
Finally, I decided to derive a key from the key user inputed. I also mentioned that in the F-Droid description, and in README file.

Fixed in version 4.1 (Commit e6937c5)
